// src/routes/playlist/[slug]/TrackListItem.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import Image from '../../../components/image/Image.svelte';
	import type { UserResponse } from '../../../types/api';
	import { formatDateToRelative } from '../../../utils/date';
	import { playerStore } from '../../../store/player';

	export let index: number;
	let element: HTMLDivElement;
	export let title: string;
	export let label_name: string;
	export let stream_url: string;
	export let created_at: string | null;
	export let artwork_url: string | null;
	export let tracks: any[] | null;
	export let user: UserResponse | null;

	const thumbnail = artwork_url ?? tracks?.[0]?.artwork_url ?? user?.avatar_url ?? null;

	onMount(() => {
		const listener = () => {
			playerStore.update((prev) => ({ ...prev, playing_url: stream_url }));
		};
		element.addEventListener('click', listener);
		return () => {
			element.removeEventListener('click', listener);
		};
	});
</script>

<div class="chat-list-item" style="top: {index * 72}px" bind:this={element}>
	<div class="flex-1 h-5 mt-1 order-1 flex content-between items-center w-full leading-messages">
		{user?.username ?? label_name}
	</div>

	<div class="chat-title relative h-5 flex items-center content-between order-0 w-full">
		<div class="chat-list-title row-title">
			<span>{title}</span>
		</div>

		{#if created_at}
			<div class="chat-list-title chat-title-right flex items-center h-5 -mt-2">
				{formatDateToRelative(created_at)}
			</div>
		{/if}
	</div>

	<div class="flex rounded-full overflow-hidden w-13 h-13 min-h-13 start-2 absolute">
		<Image src={thumbnail} alt={thumbnail} />
		<!-- {#if thumbnail}
			<img
				src={thumbnail}
				alt={thumbnail}
				loading="lazy"
				width="52"
				height="52"
				class="w-13 h-13"
			/>
		{/if} -->
	</div>
</div>

// src/widgets/TraksList/TrackListItem.tsx
"use client";

import type { TrackResponse } from "../../types/api";
import Image from "next/image";
import { formatDateToRelative } from "../../utils/date";

const TrackListItem: React.FC<TrackResponse & { index: number }> = (v) => {
  const thumbnail = v.artwork_url?.replace("-large", "-small");
  return (
    <div key={v.urn} className="chat-list-item" tabIndex={0} style={{ top: `${v.index * 72}px` }}>
      <div className="flex-1 h-5 mt-1 order-1 flex content-between items-center w-full leading-messages">
        <div>{v.label_name}</div>
      </div>

      <div className="chat-title relative h-5 flex items-center content-between order-0 w-full">
        <div className="chat-list-title row-title">
          <span>{v.title}</span>
        </div>
        <div className="chat-list-title chat-title-right flex items-center h-5 -mt-2">
          {v.created_at && formatDateToRelative(v.created_at)}
        </div>
      </div>

      <div className="flex rounded-full overflow-hidden w-13 h-13 min-h-13 start-2 absolute">
        {thumbnail && (
          <Image
            src={thumbnail?.replace("-large", "-small")}
            alt={thumbnail}
            loading="lazy"
            className="w-13 h-13"
            width={52}
            height={52}
          />
        )}
      </div>
    </div>
  );
};

export default TrackListItem;
