// src/components/virtual-list/VirtualList.svelte
<script lang="ts">
	import { writable } from 'svelte/store';
	import './list-items.css';
	import '../../routes/layout.css';
	import { onMount } from 'svelte';
	import type { UserResponse } from '../../types/api';

	export let items: any[] = [];
	export let totalCount: number;
	export let itemHeight: number = 72;
	export let ItemComponent: any;

	let limit = writable(10);
	let visibleOffset = writable(0);
	// let container: HTMLDivElement;

	function updateLimit() {
		limit.set(Math.round(window.innerHeight / itemHeight) + 6);
	}

	function handleScroll(e: Event) {
		const y = (e.target as HTMLDivElement).scrollTop;
		visibleOffset.set(Math.max(Math.round(y / itemHeight) - 2, 0));
	}
	onMount(() => {
		updateLimit();
		window.addEventListener('resize', updateLimit);
		// container.addEventListener('scroll', handleScroll);
		return () => {
			window.removeEventListener('resize', updateLimit);
			// container.removeEventListener('scroll', handleScroll);
		};
	});
</script>

<!--  -->

<div
	class="overlay-scroll scrollable bg-surface-color flex flex-col h-full"
	on:scroll|passive={handleScroll}
>
	<div
		class="mx-2 relative overflow-y-visible block shrink-0"
		style="min-height: {totalCount * itemHeight}px"
	>
		{#each items.slice($visibleOffset, $visibleOffset + $limit) as item, i (item.urn ?? i)}
			<svelte:component this={ItemComponent} {...item} index={i + $visibleOffset} />
		{/each}
	</div>
</div>

<style>
</style>

// src/widgets/VirtualList/VirtualList.tsx
import { useCallback, useEffect, useState, type ComponentType } from "react";
import type { PlaylistResponse, TrackResponse } from "../../types/api";
import "./list-items.css";

export interface VirtualListProps<T extends PlaylistResponse | TrackResponse> {
  items: T[];
  totalCount: number;
  itemHeight?: number;
  ItemComponent: ComponentType<T & { index: number }>;
}

export function VirtualList<T extends PlaylistResponse | TrackResponse>({
  items,
  totalCount,
  itemHeight = 72,
  ItemComponent,
}: VirtualListProps<T>) {
  const [limit, setLimit] = useState(10);
  const [visibleOffset, setVisibleOffset] = useState(0);

  useEffect(() => {
    if (typeof window !== "undefined") {
      const update = () => {
        setLimit(Math.round(window.innerHeight / itemHeight) + 6);
      };
      update();
      window.addEventListener("resize", update);
      return () => window.removeEventListener("resize", update);
    }
  }, [itemHeight]);

  const handleScroll: React.UIEventHandler<HTMLDivElement> = useCallback(
    (e) => {
      const y = e.currentTarget.scrollTop;
      setVisibleOffset(Math.max(Math.round(y / itemHeight) - 2, 0));
    },
    [itemHeight]
  );

  return (
    <div className="overlay-scroll bg-surface-color flex flex-col h-full" onScroll={handleScroll}>
      <div
        className="mx-2 relative overflow-y-visible block shrink-0"
        style={{ minHeight: `${totalCount * itemHeight}px` }}
      >
        {items.slice(visibleOffset, visibleOffset + limit).map((item, index) => (
          <ItemComponent
            key={item["permalink_url"] ?? index}
            {...item}
            index={index + visibleOffset}
          />
        ))}
      </div>
    </div>
  );
}
